spring:
  application:
    env: stage

demo:
  greeting: "stage profile: Welcome to Kaizen Demo Ticker Service"

logging:
  config: "classpath:logback-spring.xml"
  level:
    com.nvidia: INFO
    org.springframework.web: ERROR
