spring:
  application:
    env: prod

stock:
  greeting: 'prod profile: Hello from Config Server'

logging:
  config: "classpath:logback-spring.xml"
  level:
    com.nvidia: INFO
    org.springframework.web: ERROR
