#Spring Config
spring:
  application:
    env: default

iex:
  baseUri: https://sandbox.iexapis.com/stable/
  publishableToken: ${kv.publishableToken}
  dummyToken: ${kv.dummyToken}

logging:
  config: "classpath:logback-console.xml"
  level:
    com.nvidia: DEBUG
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      base-path: /admin
      exposure:
        include: ["health", "info"]
  endpoint:
    health:
      show-details: always
  server:
    port: 9090

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
  use-forward-headers: true
  tomcat:
    basedir: /tmp/tomcat
    accesslog:
      enabled: true
      pattern: '%{X-Forwarded-For}i %l %u %t "%r" %s %b "%{User-Agent}i" "%{Referer}i" %D'
      buffered: false

stock:
  greeting: 'default profile: Hello from Config Server'

